version: '2'
services:
  app:
    build:
      context: ./
    volumes:
      - ./:/app
    networks:
      - notes
    environment:
      DB_HOST: database
    ports:
      - '8001:80'

  database:
    image: mysql:5.6
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: notes
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '33072:3306'
    networks:
      - notes

volumes:
  dbdata:

networks:
  notes:
    driver: bridge
