services:
  app:
    context: ./
    primary: true
    exposePort: 80
    environment:
      - name: DB_HOST
        value: '127.0.0.1'
  database:
    image:
      name: jadenlemmon/evernote-db
      username: jadenlemmon
      password: ${DOCKERHUB_PASSWORD}
